### ISSUE TITLE
Preview builds 

### ISSUE THREAD

**Issue by watashinosoulsociety** [Amaan4421/YTunes#1]
Basically can you make a preview builds or release some previews for people like me who don't own a pc and can't clone your repo .. I do want to try the app out but I just can't cuz I don't own a pc or laptop of any kind to like get the application ... It'd be real helpful if you released previews or smth ... Regards

**Comment by Amaan4421** [comment]
Hi there!

Thanks for your patience and for showing interest in YTunes. I'm happy to let you know that a preview release of the app is now available for download!

You can download the APK directly from the [Releases](https://github.com/Amaan4421/YTunes/releases) section of the repository. Follow the installation instructions provided in the release notes, and you'll be able to try out the app on your device.

If you encounter any issues or have any feedback, please feel free to share it with me. Your input would be greatly appreciated!

Best regards,
Amaan
